# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paquete.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'paquete.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpaquete.proto\x12\x07paquete\"Y\n\x07Paquete\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04peso\x18\x02 \x01(\x01\x12\x13\n\x0b\x64imensiones\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x04 \x01(\t\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\"M\n\x17RegistrarPaqueteRequest\x12\x0c\n\x04peso\x18\x01 \x01(\x01\x12\x13\n\x0b\x64imensiones\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x03 \x01(\t\"7\n\x18RegistrarPaqueteResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"J\n\x1e\x41\x63tualizarEstadoPaqueteRequest\x12\x12\n\nid_paquete\x18\x01 \x01(\t\x12\x14\n\x0cnuevo_estado\x18\x02 \x01(\t\"2\n\x1f\x41\x63tualizarEstadoPaqueteResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\"\n ListarPaquetesDisponiblesRequest\"G\n!ListarPaquetesDisponiblesResponse\x12\"\n\x08paquetes\x18\x01 \x03(\x0b\x32\x10.paquete.Paquete\",\n\x16\x45liminarPaqueteRequest\x12\x12\n\nid_paquete\x18\x01 \x01(\t\"*\n\x17\x45liminarPaqueteResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"+\n\x15ObtenerPaqueteRequest\x12\x12\n\nid_paquete\x18\x01 \x01(\t\";\n\x16ObtenerPaqueteResponse\x12!\n\x07paquete\x18\x01 \x01(\x0b\x32\x10.paquete.Paquete2\xf5\x03\n\x0fPaqueteServicio\x12W\n\x10RegistrarPaquete\x12 .paquete.RegistrarPaqueteRequest\x1a!.paquete.RegistrarPaqueteResponse\x12l\n\x17\x41\x63tualizarEstadoPaquete\x12\'.paquete.ActualizarEstadoPaqueteRequest\x1a(.paquete.ActualizarEstadoPaqueteResponse\x12r\n\x19ListarPaquetesDisponibles\x12).paquete.ListarPaquetesDisponiblesRequest\x1a*.paquete.ListarPaquetesDisponiblesResponse\x12T\n\x0f\x45liminarPaquete\x12\x1f.paquete.EliminarPaqueteRequest\x1a .paquete.EliminarPaqueteResponse\x12Q\n\x0eObtenerPaquete\x12\x1e.paquete.ObtenerPaqueteRequest\x1a\x1f.paquete.ObtenerPaqueteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paquete_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAQUETE']._serialized_start=26
  _globals['_PAQUETE']._serialized_end=115
  _globals['_REGISTRARPAQUETEREQUEST']._serialized_start=117
  _globals['_REGISTRARPAQUETEREQUEST']._serialized_end=194
  _globals['_REGISTRARPAQUETERESPONSE']._serialized_start=196
  _globals['_REGISTRARPAQUETERESPONSE']._serialized_end=251
  _globals['_ACTUALIZARESTADOPAQUETEREQUEST']._serialized_start=253
  _globals['_ACTUALIZARESTADOPAQUETEREQUEST']._serialized_end=327
  _globals['_ACTUALIZARESTADOPAQUETERESPONSE']._serialized_start=329
  _globals['_ACTUALIZARESTADOPAQUETERESPONSE']._serialized_end=379
  _globals['_LISTARPAQUETESDISPONIBLESREQUEST']._serialized_start=381
  _globals['_LISTARPAQUETESDISPONIBLESREQUEST']._serialized_end=415
  _globals['_LISTARPAQUETESDISPONIBLESRESPONSE']._serialized_start=417
  _globals['_LISTARPAQUETESDISPONIBLESRESPONSE']._serialized_end=488
  _globals['_ELIMINARPAQUETEREQUEST']._serialized_start=490
  _globals['_ELIMINARPAQUETEREQUEST']._serialized_end=534
  _globals['_ELIMINARPAQUETERESPONSE']._serialized_start=536
  _globals['_ELIMINARPAQUETERESPONSE']._serialized_end=578
  _globals['_OBTENERPAQUETEREQUEST']._serialized_start=580
  _globals['_OBTENERPAQUETEREQUEST']._serialized_end=623
  _globals['_OBTENERPAQUETERESPONSE']._serialized_start=625
  _globals['_OBTENERPAQUETERESPONSE']._serialized_end=684
  _globals['_PAQUETESERVICIO']._serialized_start=687
  _globals['_PAQUETESERVICIO']._serialized_end=1188
# @@protoc_insertion_point(module_scope)
