# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cliente_pb2 as cliente__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cliente_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClienteServicioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarCliente = channel.unary_unary(
                '/cliente.ClienteServicio/RegistrarCliente',
                request_serializer=cliente__pb2.RegistrarClienteRequest.SerializeToString,
                response_deserializer=cliente__pb2.RegistrarClienteResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/cliente.ClienteServicio/Login',
                request_serializer=cliente__pb2.LoginRequest.SerializeToString,
                response_deserializer=cliente__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ActualizarCliente = channel.unary_unary(
                '/cliente.ClienteServicio/ActualizarCliente',
                request_serializer=cliente__pb2.ActualizarClienteRequest.SerializeToString,
                response_deserializer=cliente__pb2.ActualizarClienteResponse.FromString,
                _registered_method=True)
        self.EliminarCliente = channel.unary_unary(
                '/cliente.ClienteServicio/EliminarCliente',
                request_serializer=cliente__pb2.EliminarClienteRequest.SerializeToString,
                response_deserializer=cliente__pb2.EliminarClienteResponse.FromString,
                _registered_method=True)
        self.ObtenerCliente = channel.unary_unary(
                '/cliente.ClienteServicio/ObtenerCliente',
                request_serializer=cliente__pb2.ObtenerClienteRequest.SerializeToString,
                response_deserializer=cliente__pb2.ObtenerClienteResponse.FromString,
                _registered_method=True)


class ClienteServicioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClienteServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarCliente,
                    request_deserializer=cliente__pb2.RegistrarClienteRequest.FromString,
                    response_serializer=cliente__pb2.RegistrarClienteResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=cliente__pb2.LoginRequest.FromString,
                    response_serializer=cliente__pb2.LoginResponse.SerializeToString,
            ),
            'ActualizarCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCliente,
                    request_deserializer=cliente__pb2.ActualizarClienteRequest.FromString,
                    response_serializer=cliente__pb2.ActualizarClienteResponse.SerializeToString,
            ),
            'EliminarCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarCliente,
                    request_deserializer=cliente__pb2.EliminarClienteRequest.FromString,
                    response_serializer=cliente__pb2.EliminarClienteResponse.SerializeToString,
            ),
            'ObtenerCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCliente,
                    request_deserializer=cliente__pb2.ObtenerClienteRequest.FromString,
                    response_serializer=cliente__pb2.ObtenerClienteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cliente.ClienteServicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cliente.ClienteServicio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClienteServicio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente.ClienteServicio/RegistrarCliente',
            cliente__pb2.RegistrarClienteRequest.SerializeToString,
            cliente__pb2.RegistrarClienteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente.ClienteServicio/Login',
            cliente__pb2.LoginRequest.SerializeToString,
            cliente__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente.ClienteServicio/ActualizarCliente',
            cliente__pb2.ActualizarClienteRequest.SerializeToString,
            cliente__pb2.ActualizarClienteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente.ClienteServicio/EliminarCliente',
            cliente__pb2.EliminarClienteRequest.SerializeToString,
            cliente__pb2.EliminarClienteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente.ClienteServicio/ObtenerCliente',
            cliente__pb2.ObtenerClienteRequest.SerializeToString,
            cliente__pb2.ObtenerClienteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
