# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cliente.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cliente.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcliente.proto\x12\x07\x63liente\"^\n\x17RegistrarClienteRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x65\x64ula\x18\x02 \x01(\t\x12\x10\n\x08telefono\x18\x03 \x01(\t\x12\x11\n\tdireccion\x18\x04 \x01(\t\"+\n\x18RegistrarClienteResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\x1e\n\x0cLoginRequest\x12\x0e\n\x06\x63\x65\x64ula\x18\x01 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"_\n\x18\x41\x63tualizarClienteRequest\x12\x0e\n\x06\x63\x65\x64ula\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08telefono\x18\x03 \x01(\t\x12\x11\n\tdireccion\x18\x04 \x01(\t\",\n\x19\x41\x63tualizarClienteResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"(\n\x16\x45liminarClienteRequest\x12\x0e\n\x06\x63\x65\x64ula\x18\x01 \x01(\t\"*\n\x17\x45liminarClienteResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\'\n\x15ObtenerClienteRequest\x12\x0e\n\x06\x63\x65\x64ula\x18\x01 \x01(\t\"]\n\x16ObtenerClienteResponse\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x65\x64ula\x18\x02 \x01(\t\x12\x10\n\x08telefono\x18\x03 \x01(\t\x12\x11\n\tdireccion\x18\x04 \x01(\t2\xa7\x03\n\x0f\x43lienteServicio\x12W\n\x10RegistrarCliente\x12 .cliente.RegistrarClienteRequest\x1a!.cliente.RegistrarClienteResponse\x12\x36\n\x05Login\x12\x15.cliente.LoginRequest\x1a\x16.cliente.LoginResponse\x12Z\n\x11\x41\x63tualizarCliente\x12!.cliente.ActualizarClienteRequest\x1a\".cliente.ActualizarClienteResponse\x12T\n\x0f\x45liminarCliente\x12\x1f.cliente.EliminarClienteRequest\x1a .cliente.EliminarClienteResponse\x12Q\n\x0eObtenerCliente\x12\x1e.cliente.ObtenerClienteRequest\x1a\x1f.cliente.ObtenerClienteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cliente_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRARCLIENTEREQUEST']._serialized_start=26
  _globals['_REGISTRARCLIENTEREQUEST']._serialized_end=120
  _globals['_REGISTRARCLIENTERESPONSE']._serialized_start=122
  _globals['_REGISTRARCLIENTERESPONSE']._serialized_end=165
  _globals['_LOGINREQUEST']._serialized_start=167
  _globals['_LOGINREQUEST']._serialized_end=197
  _globals['_LOGINRESPONSE']._serialized_start=199
  _globals['_LOGINRESPONSE']._serialized_end=248
  _globals['_ACTUALIZARCLIENTEREQUEST']._serialized_start=250
  _globals['_ACTUALIZARCLIENTEREQUEST']._serialized_end=345
  _globals['_ACTUALIZARCLIENTERESPONSE']._serialized_start=347
  _globals['_ACTUALIZARCLIENTERESPONSE']._serialized_end=391
  _globals['_ELIMINARCLIENTEREQUEST']._serialized_start=393
  _globals['_ELIMINARCLIENTEREQUEST']._serialized_end=433
  _globals['_ELIMINARCLIENTERESPONSE']._serialized_start=435
  _globals['_ELIMINARCLIENTERESPONSE']._serialized_end=477
  _globals['_OBTENERCLIENTEREQUEST']._serialized_start=479
  _globals['_OBTENERCLIENTEREQUEST']._serialized_end=518
  _globals['_OBTENERCLIENTERESPONSE']._serialized_start=520
  _globals['_OBTENERCLIENTERESPONSE']._serialized_end=613
  _globals['_CLIENTESERVICIO']._serialized_start=616
  _globals['_CLIENTESERVICIO']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
