# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import envio_pb2 as envio__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in envio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvioServicioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarEnvio = channel.unary_unary(
                '/envio.EnvioServicio/RegistrarEnvio',
                request_serializer=envio__pb2.RegistrarEnvioRequest.SerializeToString,
                response_deserializer=envio__pb2.RegistrarEnvioResponse.FromString,
                _registered_method=True)
        self.HistorialEnvios = channel.unary_unary(
                '/envio.EnvioServicio/HistorialEnvios',
                request_serializer=envio__pb2.HistorialEnviosRequest.SerializeToString,
                response_deserializer=envio__pb2.HistorialEnviosResponse.FromString,
                _registered_method=True)


class EnvioServicioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarEnvio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HistorialEnvios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvioServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarEnvio': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarEnvio,
                    request_deserializer=envio__pb2.RegistrarEnvioRequest.FromString,
                    response_serializer=envio__pb2.RegistrarEnvioResponse.SerializeToString,
            ),
            'HistorialEnvios': grpc.unary_unary_rpc_method_handler(
                    servicer.HistorialEnvios,
                    request_deserializer=envio__pb2.HistorialEnviosRequest.FromString,
                    response_serializer=envio__pb2.HistorialEnviosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'envio.EnvioServicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('envio.EnvioServicio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvioServicio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarEnvio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/envio.EnvioServicio/RegistrarEnvio',
            envio__pb2.RegistrarEnvioRequest.SerializeToString,
            envio__pb2.RegistrarEnvioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HistorialEnvios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/envio.EnvioServicio/HistorialEnvios',
            envio__pb2.HistorialEnviosRequest.SerializeToString,
            envio__pb2.HistorialEnviosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
