# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'envio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65nvio.proto\x12\x05\x65nvio\"T\n\x05\x45nvio\x12\x10\n\x08id_envio\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x65\x64ula_cliente\x18\x02 \x01(\t\x12\x12\n\nid_paquete\x18\x03 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x04 \x01(\t\"C\n\x15RegistrarEnvioRequest\x12\x16\n\x0e\x63\x65\x64ula_cliente\x18\x01 \x01(\t\x12\x12\n\nid_paquete\x18\x02 \x01(\t\";\n\x16RegistrarEnvioResponse\x12\x10\n\x08id_envio\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"0\n\x16HistorialEnviosRequest\x12\x16\n\x0e\x63\x65\x64ula_cliente\x18\x01 \x01(\t\"7\n\x17HistorialEnviosResponse\x12\x1c\n\x06\x65nvios\x18\x01 \x03(\x0b\x32\x0c.envio.Envio2\xb0\x01\n\rEnvioServicio\x12M\n\x0eRegistrarEnvio\x12\x1c.envio.RegistrarEnvioRequest\x1a\x1d.envio.RegistrarEnvioResponse\x12P\n\x0fHistorialEnvios\x12\x1d.envio.HistorialEnviosRequest\x1a\x1e.envio.HistorialEnviosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIO']._serialized_start=22
  _globals['_ENVIO']._serialized_end=106
  _globals['_REGISTRARENVIOREQUEST']._serialized_start=108
  _globals['_REGISTRARENVIOREQUEST']._serialized_end=175
  _globals['_REGISTRARENVIORESPONSE']._serialized_start=177
  _globals['_REGISTRARENVIORESPONSE']._serialized_end=236
  _globals['_HISTORIALENVIOSREQUEST']._serialized_start=238
  _globals['_HISTORIALENVIOSREQUEST']._serialized_end=286
  _globals['_HISTORIALENVIOSRESPONSE']._serialized_start=288
  _globals['_HISTORIALENVIOSRESPONSE']._serialized_end=343
  _globals['_ENVIOSERVICIO']._serialized_start=346
  _globals['_ENVIOSERVICIO']._serialized_end=522
# @@protoc_insertion_point(module_scope)
